### ISSUE TITLE
Single host runreport not working? 

### ISSUE THREAD

**Issue by kmannthey** [mlcommons/storage#22]
I did a run on a single host:
```
./benchmark.sh run --workload unet3d --num-accelerators 8 --results-dir unet3d_results-1 --param dataset.data_folder=/panfs/pgh-realm-75-4/r6-256/unet3d/ --param dataset.num_files_train=3200
```

after the run it seems like json files were created ok? 

``
[root@pgh-echo-1-1 storage]# ls unet3d_results-1/
0_output.json  1_output.json  2_output.json  3_output.json  4_output.json  5_output.json  6_output.json  7_output.json  configs  dlio.log  per_epoch_stats.json  summary.json
``

When I do the reportgen it says I need a multi-host type format? 

``
[root@pgh-echo-1-1 storage]# ./benchmark.sh reportgen -r unet3d_results-1
2023-05-04 16:11:20 Error: Directory structure unet3d_results-1/summary.json is not correct. It has be in format result_dir/run(1..n)/host(1..n)/summary.json
``

I don't see instructions in the readme for how to do multi-host but I will look in benchmark.sh for more details. 

I tried to fake the multi home layout it asked for but that did not work. 

``
[root@pgh-echo-1-1 storage]# mkdir  unet3d_results-onehost-8
[root@pgh-echo-1-1 storage]# mkdir  unet3d_results-onehost-8/run1
[root@pgh-echo-1-1 storage]# mkdir  unet3d_results-onehost-8/run1/host1/
[root@pgh-echo-1-1 storage]# cp -rf unet3d_results-1/* unet3d_results-onehost-8/run1/host1/
[root@pgh-echo-1-1 storage]# ./benchmark.sh reportgen -r unet3d_results-onehost-8/
2023-05-04 16:14:21 Error: AU value didn't pass the threshold in the run reported by unet3d_results-onehost-8/run1/host1/summary.json
``

Let me know if there are any suggestions.

**Comment by kmannthey** [comment]
@johnugeorge  the first one was just a test run. 

A new one today. 

`[root@pgh-echo-1-1 storage]# ./benchmark.sh reportgen -r unet3d_results-2ppn-8nodes/unet3d_results-pgh-echo-2-2.palab.panasas.com-log-2ppn-8nodes/
2023-05-05 16:14:30 Error: Directory structure unet3d_results-2ppn-8nodes/unet3d_results-pgh-echo-2-2.palab.panasas.com-log-2ppn-8nodes/summary.json is not correct. It has be in format result_dir/run(1..n)/host(1..n)/summary.json
`

**Comment by johnugeorge** [comment]
results directory should be in format provided in the https://github.com/mlcommons/storage#configuration. Can you verify?
