### ISSUE TITLE
Update DLRM mentions in readme, etc.

### ISSUE THREAD

**Issue by TheKanter** [mlcommons/storage#28]
First of all, the https://github.com/mlcommons/storage/blob/main/README.md is beautiful and really nicely done!

Since DLRM isn't in first version, so rather than saying "todo", can we explicitly indicate that?

**Comment by johnugeorge** [comment]
Created: https://github.com/mlcommons/storage/pull/30

**Comment by johnugeorge** [comment]
This is resolved with #30
